### PR TITLE
use defaults via docopt

### PR DESCRIPTION
**Pull request by esc**
Here is a way to use the default mechanism from docopt.

### CODE REVIEW

**Comment by esc** [comment]
Although the tests are still failing and I'm not sure how to test this w/o cram.

**Comment by sdomme** [comment]
It's a good idea. I will first resolve the conflicts.

**Comment by esc** [comment]
Yeah, it is nice. This way the user can see from the help screen what the defaults are and the logic for handling them is eliminated.

**Comment by esc** [comment]
You ought to write some cram tests, btw...

**Pull request merged**
